version: "3.7"
services:
  springapp:
    container_name: springbootapp
    build: 'C:\Users\Amine\Documents\GitHub\ProjetDevops'
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/kadem?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped

    image: "damine99/kaddem:1.8"
    depends_on:
      - db-mysql

  db-mysql:
    image: "mysql:5.6"
    container_name: dbmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      #- MYSQL_DATABASE=job
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
networks:
  springapimysql-net:

volumes:
  db: